name: voter_tester
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  pointycastle: ^3.0.1
  #shared_preferences: ^2.0.5
  #sqflite: ^2.0.0+3
  uuid: ^3.0.4
  sqflite_common_ffi: ^2.0.0
  sqlite3: ^1.1.2
  http: ^0.13.1
  args: ^2.1.1

